title: "mvtta, scientific developer log"
author: Mariana Valdetaro
email: mvaldeta42@gmail.com
discription: Welcome
safe: true
source: "https://github.com/mvtta/mvtta.github.io"
#lsi: false

# build settings
theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
#incremental: false
#highlighter: rouge
#gist:
  #  noscript: false

---
