project:
  type: website
  output-dir: _output

website:
  title: "/"
  navbar: 
    background: black
    search: true
    left:
      - text: "Agency"
        file: posts/Agency
      - text: "Articles"
        file: posts/Articles
      - text: "Experiments"
        file: posts/Experiments
      - text: "Notebooks"
        file: posts/Notebooks
      - text: "Thoughts"
        file: posts/Thoughts
      - text: "Resource-Tree"
        file: resource-tree.qmd


format:
  html:
    theme: cyborg
    font: inter
    css: styles.css



