project:
  type: website
  output-dir: docs

website:
  title: "mvtta"
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - resume.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true


