project:
  type: website
  output-dir: _output

website:
  title: "/"
  navbar: 
    background: black
    search: true
    left:
      - text: "Open Notes"
        file: posts/Introduction/index.qmd
      - text: "Essays"
        file: essays/index.qmd
      - text: "Poems"
        file: poems/poems-and-thoughts.qmd
      - text: "Infix"
        file: context.qmd

format:
  html:
    theme: cyborg
    font: inter
    css: styles.css



