project:
  type: website
  output-dir: _output

website:
  title: "mvtta"
  navbar: 
    background: black
    search: true
    left:
      - text: "context"
        file: index.qmd
      - text: "log"
        file: log.qmd
format:
  html:
    theme: cyborg
    css: styles.css



