---
title: "infix/"
listing:
    categories: true
categories: [references]
toc: true
href:
    color: white
---

## Information
0. Theories
    - [The experience of life is an information process](https://arxiv.org/abs/1210.5908)

## Evolution
1.  Evolutionary Biochemistry
    -   Bio-Chemistry
        -   [Nick Lane](https://nick-lane.net/publications/)
            -   [The electrical origins of life](https://www.youtube.com/watch?v=FLaTU-t1CQM "The electrical origin of life")
            -   [Kreb Cycle](https://youtu.be/vBiIDwBOqQA?si=o8golhRao2R4NXIH "Kreb Cycle")
            -   <https://nick-lane.net/publications/a-biophysical-basis-for-the-emergence-of-the-genetic-code-in-protocells/>
            -   <https://nick-lane.net/publications/origin-eukaryotic-cell/>
            -   <https://www.nature.com/articles/s41570-019-0155-6>
    -   [Bio-Electricity](Bioelectricity:%20From%20Cognitive%20Glue%20to%20Regenerative%20Medicine%20with%20Special%20Focus%20on%20Microbiology/Immunology)
    -   Digital Chemistry
        -   Assembly Theory vs Co-evolution
        -   [Assembly theory explains and quantifies selection and evolution](https://www.nature.com/articles/s41586-023-06600-9)
    -   Biology
        -   Michael Levin
            -   [Papers](https://drmichaellevin.org/publications/)
            -   [Presentations](https://drmichaellevin.org/presentations/)
        -   Theory for Mind Everywhere
    -   Computational Biology
        -   Von Neuman
        -   Turin Biology Paper
            -   Cellular Automata
                -   <https://slackermanz.com/explorations-of-cellular-automata-and-complex-systems/>
                -   <https://softologyblog.wordpress.com/2018/03/31/more-explorations-with-multiple-neighborhood-cellular-automata/>

## Physics
2.  Physics
    -   Borrowing "The Pixel of Reality" from Quantum Gravity Theory

## Philosophy
3. Philosophy
    -   Cognition
    -   Meaning & Goals
    -   [Meta-Crisis](https://www.youtube.com/watch?v=4kBoLVvoqVY)
    -   Autopoiesis, Homeostasis

## Ecology
4.  Ecology

## Complex Systems
5.  Complex Systems
    -   Information
    -   Graph Problems

##  Political Science & governance
6.  Political Science & Governance
    -   Democracy
        -   Hongs Formula
        -   Re-visiting the majority
        -   Outliers value
    -   Governance
        -   Topology of governance
        -   Spatial relationship

##  Problems Identified
7.  Problems Identified
    -   Identified Problems: A summary

## Interactions
8.  Convergence / Justaposition
    -   Emergence
    -   Scale and Abstraction
    -   Continuum and growth rate
    -   Outliers value
    -   Graphing the intuitive relationship
    -   Testing the relationship by formal logic

##  Solutions
9.  Solutions and their viability
    -   For global agreement
        -   Common ground for mutual understanding
        -   Party analogy
        -   Human desires in Ven diagram
    -   Global agreement, local action.
    -   Using Ramsey Numbers and graphs of connections to predict hierarchical models for communities to self-organize / self Governance
    -   Models and policies for truth
    -   Peer-To-Peer Fact Validator
    -   Artificial Resource

## Civilization
10. Civilization Design
    -   Axioms
    -   Boundaries
    -   Agreements

## Portugal
11. Portugal
    -   A letter
    -   Modeling direct democracy in the current context
    -   Exposing polarizing incentives
    -   Demystifying / unblocking inductive bias holding back humanity

Would you like to have a conversation on these topics? [Contact me @](mailto:mvaldeta42@gmail.com)