---
title: "poems/"
format:
  html:
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
author: "Valdetaro, M"
date: "2024-01-23"
categories: [poems, thoughts, drawings]
---

    I don't know what to do
    Where to start?
    To do for others 
    my body goes
    my mind follows
    to do for me
    body is made of iron 
    
------------------------------------------------------------------------

    For years
    All that was known 
    reality
    was mainly pain and scarcity 
    lack of
    being chased by 
    death.
    One day
    near the end
    rain came
    space was being shared
    the weather changed
    and the moons, 
    fertility
    no more drought 
    no more loneliness
    for the small cactus. 
    241120


## Places

    There is a place that does fully exist, where you live. A place where thoughts and guts get intertwined.
    A place where there's only room for parts, mirrors.
    There is yet another place where the grounding forces reside where one rests.
    In the soil, intestines are roots.

## Where is there to navigate?

    Where is there to navigate? Plans are mere distractions Contractions of freedom though, 
    with love I draft with you, Life. Planing is dreaming, a commitment to oneself, an engagement, 
    between the now and the future. 
    Is signing on the Book of Life.
    Often, also a whole strategy, to survive in harsh environments, previsions of hope Quixotean echos. Giants, 
    or nothing at all.

## Walking under the rain

    I'd rather think than not. Seems rather simple, but think about it. 
    Do it for more than a minute, and no I did not ask your opinion, only your thoughts.
    How quickly you ended the conversation, I wish I had better skills to engage you in the discussion. 
    I disagree with your premise, do you care to elaborate?\
    Wait, let's talk more.


## D. Rute I

    Dona Rute, is so beautiful today, looking up at her against the blue sky with her blue eyes skin glazed with time, 
    closeness, love. Fearless, within her world.
    The weather was pleasant and soft.
    Experience transcends formulation, there is no concept or framework to explain, 
    the emotion present in that moment.


## Venting

    Made of particles glued with toxins crumbs of all crushing movement inaction 
    silence decay alike all residents disloyal exchange wind feeding flames undeserving fools.

    Do not know incomprehensible incapable unpredictable unchaste unfolded auction 
    anduction on trial vial unnatandace dancing the nothingness.
    The gift of further breaking was humbled by some gracious voice audible at a distance.

------------------------------------------------------------------------

    A line light longing threading oscillation oyster alluring luck cease prickling titillating gimmick resemblance

------------------------------------------------------------------------

### The process  

To understand it, is a waste of time.   
The process of the process of the process                                                                          Any kind of self-inflicted suffering is a waste of time.                                                                            Albeit any or many attempts, trying is also a waste of time.                                                                            So, what does matter? (As in relevant, essential)                                                                       When wasting the same time, pondering how different narrative scenarios impact the lost moments of one's existence, does anything beyond this moment matter? What would be appropriate, as a trajectory, from here, to there? |

### Weight

Hoje sinto-me pesada,
pesada o suficiente para me sentir presa ao chão.
Também me sinto fraccionada ao ponto de me desintegrar,
quase quebro,
precede o estímulo.
Não me parece que tenha razões para isso.

Não sei o que fazer e não consigo fazer nada.
Sinto-me aflita, gostava de conseguir abrir um buraco no diafragma e tirar com as minhas mãos o parasita.
301222


## Routine

    Um lugar comum, banal e até estupido, diria.
    Claro, com uma grande carga julgativa sob o observado.
    Mesmo assim, continuo sem pudor: São ondas, que é como quem diz,
    Oscilações.
    Como identificar as partes, das partes que compõem as ondas?
    Que sem nome, o atrapalham coitado.
    Mareado, enjoado, apresenta num quadro,
    O que seria esperado não sai,
    Era simples, a audiência está inquieta, jugo que julga também,
    coitado.
    Sai do mar apavorado, quase cai.
    As ondas batem nas cadeiras do escritório,
    todos tem os seus sapatos, bem engraxado, agora manchados agora de sal.
    O sal queima.
    A reunião da manhã descai sobre as horas não convencionadas.
    A culpa é dele que não se preparou, para as vagas rotineiras.
    Quem se surpreende com a rotina.
    Será um raro distúrbio, ainda não diagnosticado,

    que aflige aqueles pobres coitados,
    normais por fora mareados por dentro?
    51223

Where you were doomed to be unhappy,
It elapsed into a far away dimmed memory.
Perhaps time diluted itself in ancient cries 
And gave birth to the void where this infant thread weaves you and everything, anew. 


When in an abyss of darkness,
Jump.
If facing a wall,
Climb.
Some die of exhaustion
And not risk. 

Reality collapsed 
There’s blood and flesh everywhere
Remainders of dreams
Teeth and hair
Particles collapsed 
Lost their magnetic charge
Let the poison of the debris contaminate 
Decompose
After all the seconds
A pause. 

Solitude is a sinful waist of time
If you’re only good by yourself
And by good I mean less bad but still in pain
Within the walls of your house
A dormant vulcano
Outside life creates itself.
Some say that from pain comes growth,
But from constant pain comes decay 
Hope vanishes
And the energy to pretend you’re not hurt 
Slowly fades.
When all you know is pain,
You’ll make everyone suffer either way. 

I’m a raccoon, underground, feeding from rests
Living a simple life,
Until death. 

If color returns
I’ll quit blindness 


The journey of an ant 

There is blood in the stairs,
Is it mine?
I see blood on my desk,
Is it mine?
What difference does it make.


Uma dança de figuras reflectidas em painéis translúcidos molhados com lágrimas de Deus e suor desumano, dejectos defuntos d’almas queimadas na hora de ser. Aqui quem sabe foi no ar lamber o sal do mar para matar a sede de ser. Lá ao longe há um dó de sol e lá também haverá morte que corre pelas nove montanhas de dor, pronta a beber. 

There’s fine line of fine paper of fine cotton of fine plants of fine sun of fine galaxy of fine fusion of fine dust of fine sugar cube of fine nothing. 

Caring is the great escape, the sweet opium.

Anchors, drown me. Pull me hard, don’t let me float to relief. Lock me in the world of Men, in this shell of meat, always thirsty. Ground me at the bottom of the sea of sadness. Keep me even if I cry, so I can die amongst mortals, of old age or chance. 
Anchors, may you find in my suffering also my praise of gratitude. 

My knees hurt from existence

Time, 
Is l measurement in the making. 
Term of inexistence.
Maybe time is like a huge cunning wave, destructive and indifferent. 
Maybe we the lonely buoy that in a life time of hostility never moves from the birthplace.
Human perspective of time is not relevant to it.
It is not a measurement within Human domain, it’s untainted. 



TEM TEMPO 
TEM TEMPO 
PRESENTE
AGUA QUENTE
FOI NO AR PARA DAR 
DIZER ADEUS 
QUANDO RESPIRAR 
FOI QUEM SABE 
ALGUEM QUE SABE VOAR 
DOA A QUEM DOER 
BONITO DE SE VER 
MEL NO AR 
DO ANTIGAMENTE 
DESAJEITAR 
O AQUI FICAR 
SE VAIS NEM VENS 
QUERO TE AQUI 
LAVO AS MÃO 
FOI O QUE PERDI 


