---
title: "Poems, Thoughts, Loose Notes & Drawings"

---

author: "Valdetaro, M"
date: "2024-01-23"
categories: [poems, thoughts, drawings]
---

**Assorted**

------------------------------------------------------------------------

Adjusting the power distribution in democratic exercise and functions 

through a revisited direct, governance-by-peers framework?

923

------------------------------------------------------------------------

Not suitable for

becomes free of.

923

------------------------------------------------------------------------

I don't know what to do

Where  to start?

To do for others 

my body goes

my mind follows

to do for me

body is made of iron 

15123

------------------------------------------------------------------------

All my notes from 2022 disappeared 

vanished

the notebook got wet

I feel loss

ps:investigate how to retrieve memories 

step 1, how are memories encoded?

1511123

------------------------------------------------------------------------

For years

All that was known 

reality

was mainly pain and scarcity 

lack of

being chased by 

death.

One day

near the end

rain came

space was being shared

the weather changed

and the moons, 

fertility

no more drought 

no more loneliness

for the small cactus. 

241120

------------------------------------------------------------------------

An inventory for continuous self discovery 

4423

------------------------------------------------------------------------

Perhaps balance finds us

while we’re looking for a purely semantic 

and abstract concept

that does not exist at all.

31222

------------------------------------------------------------------------

What would change if an advanced 

technological civilization existed prior to 7000 bc?

What would that make of us?

151122

------------------------------------------------------------------------

Many years ago I started questioning the absurdity of human generated fictions

Now it’s more evident than ever

How can one escape the illusion 

and simply enjoy existing 

without words 

with no threads

being without being seen.

151122

## Places

There is a place that does fully exist, where you live. A place where thoughts and guts get intertwined.

A place where there's only room for parts, mirrors.

There is yet another place where the grounding forces reside where one rests.

In the soil, intestines are roots.

------------------------------------------------------------------------

## Where is there to navigate?

Where is there to navigate? Plans are mere distractions Contractions of freedom though, with love I draft with you, Life. Planing is dreaming, a commitment to oneself, an engagement, between the now and the future. Is signing on the book of life.

Often, also a whole strategy, to survival on harsh environments, previsions of hope Quixotean echos. Giants, Or nothing at all.

------------------------------------------------------------------------

## Walking under the rain

I'd rather think than not. Seems rather simple, but think about it. Do it for more than a minute, and no I did not ask your opinion, only your thoughts.

How quickly you ended the conversation, I wish I had better skills to engage you in the discussion. I disagree with your premise, do you care to elaborate?\
Wait, lets talk more.

------------------------------------------------------------------------

## D. Rute I

Dona Rute, so beautiful today, looking up to her against the blue sky with her blue eyes skin glazed with time, closeness, love. Fearless, withing her world.

The weather was pleasant and soft.

Experience transcends formulation, there is no concept or framework to explain, the emotion present in that moment.

------------------------------------------------------------------------

## Letters to Youth I

So be vast, and grow. Fill the emptiness and the hollows with your passion, go.

------------------------------------------------------------------------

## #Venting

Made of particles glued with toxins crumbs of all crushing movement innaction silence decay alike all residents desloyal exchange wind feeding flames undeserving fools.

------------------------------------------------------------------------

Do not know incomprehensible incapable unpredictable unchast unfolded auction anduction on trial vial unnatandace dancing the nothingness.

The gift of further breaking humbled by some gracious voice audible at a distance.

------------------------------------------------------------------------

a line light longing threading oscillation oyster alluring luck cease prickling titillating gimmick resemblance

------------------------------------------------------------------------

Is the absence of secondary goals a natural state or a capitalist inconvenient? Are all inconvénients exploitable? 210922

------------------------------------------------------------------------

## On Social Systems

It's not possible to decapitate an infrastructure.

It daunts me.

------------------------------------------------------------------------

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### The process                                                                                                                                                                                                               |
|                                                                                                                                                                                                                               |
| The process of the process of the process                                                                                                                                                                                     |
|                                                                                                                                                                                                                               |
| To understand it, a waste of time.                                                                                                                                                                                            |
|                                                                                                                                                                                                                               |
| Any kind of self inflicted suffering is a waste of time.                                                                                                                                                                      |
|                                                                                                                                                                                                                               |
| Albeit any or many attempts, trying is also a waste of time.                                                                                                                                                                  |
|                                                                                                                                                                                                                               |
| So, what does matter? (As in relevant, essential)                                                                                                                                                                             |
|                                                                                                                                                                                                                               |
| When wasting the same time, pondering how different narrative scenarios impact the lost moments of one's existence, does anything beyond this moment matter? What would be appropriate, as a trajectory, from here, to there? |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### Weight

Hoje sinto-me pesada,

pesada o suficiente para me sentir presa ao chão.

Também me sinto fraccionada ao ponto de me desintegrar,

quase quebro,

precede o estímulo.

Não me parece que tenha razões para isso.

Não sei o que fazer e não consigo fazer nada.

Sinto-me aflita, gostava de conseguir abrir um buraco no diafragma e tirar com as minhas mãos o parasita.

301222

------------------------------------------------------------------------

## Routine

Um lugar comum, banal e até estupido, diria.

Claro, com uma grande carga julgativa sob o observado.

Mesmo assim, continuo sem pudor: São ondas, que é como quem diz,

Oscilações.

Como identificar as partes, das partes que compõem as ondas?

Que sem nome, o atrapalham coitado.

Mareado, enjoado, apresenta num quadro,

O que seria esperado não sai,

Era simples, a audiência está inquieta, jugo que julga também,

coitado.

Sai do mar apavorado, quase cai.

As ondas batem nas cadeiras do escritório,

todos tem os seus sapatos, bem engraxado, agora manchados agora de sal.

O sal queima.

A reunião da manhã descai sobre as horas não convencionadas.

A culpa é dele que não se preparou, para as vagas rotineiras.

Quem se surpreende com a rotina.

Será um raro distúrbio, ainda não diagnosticado,

que aflige aqueles pobres coitados,

normais por fora mareados por dentro?

51223

------------------------------------------------------------------------

------------------------------------------------------------------------

## Origin of life

Self destruction, unintentional Stars fusing iron the course of availability birds?

Agency → Consciousness → Primal

My existence is nothing Intriguing nonetheless Why are we conscious?

Cells aware with their surroundings local consciousness?

1023

------------------------------------------------------------------------