---
title: "End of the 2023, reflections"
page-layout: article
author: "Valdetaro, M"
date: "2023-12-31"
---

The tone of this essay is emotional, untethered, free from any format constraint. 
It has no destination but the message itself. 

To pursue knowledge is to honor the gift of life. 
From our mothers to our ancestors, all of them, we owe it, to the past, ad continuum.

In the year 2023, in the christian time-stamp, we live in a period where wonder decayed into pessimism. 
Some would argue that this pessimism is a fruit directly ripped from the knowledge we seek, "perhaps we man are evil beings", "a virus we are".  

I strongly disagree, we are not evil, but ignorant. 

We may think that we have far past the dark ages of mysticism, but the enlightenment wasn't any cure for this malady that affects this global civilization.

Ignorance, and only that. 
To attribute morality to natural objects is a clear indication that we, as Humans, have not entertained the connection between ourselves and all the other life-scales. 

For now, we still haven't perceived that life is a continuum, on which we are its part and agency. 
Not only Nature has birthed us, but has incumbent on us the majestic responsibility to act on its behalf. 

We surely are not doing justice in this delegation of agency, perhaps because man chooses to oblivion, and dismisses the underlying mechanism, the logic behind agency in natural processes. 

Men and their perception need to identify the breadcrumbs left by our Mother, we are not a single thread, detached, checked out, the fruit of random causation. 

There seems to be no evidence supporting randomness in natural iterative design, only a scope of possibilities given a certain state of constraints, future agency by exploratory and combinatorial means.

What if we were to rejoice in the wonder?
To achieve constructivism, we must first admit defeat.

Ignorance is a blank page on a notebook, where we can shape the immaterial manifestation of all the mothers and the fathers, the seeds of knowledge leading to observations, sense-making, discovery and emergence. 

Let us put down the distractions, reject conformity and think. 
What we came to name "the mind" is an evolutionary device that has been developing since the beginning of life-time. 

Life-time seems to be a continuum, the stage where life is assembled by building blocks driven by potential, where actors of molecular intelligence, memory at the smallest scale, and atomic units of agency, lead to larger systems at play in the interconnectedness of all there is. 

In the scenario of the above proposed, it is understandable our ignorance, and condemnation is easy but not useful.

*[unfinished]*
Porto, Portugal, 05:30 am






