---
title: "Postulation on Levin and Lane's continnum and emergent properties on cognitive systems at scale"
page-layout: article
author: "Valdetaro, M"
date: "2023-12-31"
---

Levin prposes on his lectures ont he TOME, a prespective of space and events in the stage of a continuum developement, therefore integrating problems spaces, agency and cognition into time-line of evolutionary devices.
Lane's works on seems to futher support the role of bio-eletricity in agency , basal awareness and metabolic transactions, and as he beautifully   suggets , as  a  primary phenomena in  the origin  od life in  protocells. 

Postulation on  both premisses, and concatenating both frameworks, a continuum can  look  like  this:

Up untill this moment the separation and antagonization of different study  and academic fields led to a global understanding that cannpot, by  design, agree with  one another,  
in this paper concepts will get on  purpose intertwineed and adjoined, in an exploratory fashion, and  attempts to recponcile natural organoization  categories, not as static phenomena  but as milestones in evolutionary porocessees, not random, but iterative,  and then will tackle the glue or ajoining mechaninsm that allow milestone atchivement. 

Hogher porder of complexity seems to deman abandonment, of sacrifice of the oroblematic over reductions or incomprehensability. This baflking experience seems to indicate a faalty background or a lack of perceptual capability  from the obserber part. Yet, both lane and levin in their work, conceptualiozes as abstract framework that allows for highlevel thinkiong of the problematic of  complexity.  Moreover  the concep or radical locality in agency and the  emmergenc of extra-contextual propreties (buckminter) seem to fit this thematic and serve as an empirical design tool to visually  mark oin the continuum.

(........... explain fig continuum
1. Separate / name the  catgonies to make the ground for categorizing the ajoining matter)
2. Find name for social immateriality

Whitin this framwork, cellular networks seem to to entoity  X as bioelectricity is to celular agency in basal cognition, in  living organisms and so, whart other emergent properties thete  is ithat a joind loiving organinsm and scoial organismms 
And then social behavior has been  treated  as  a either social sciencve or unseol;ved probalitistic mathematical problem  when prhaps woithing this phramwork we can reduce it to wahr priot whas just  physocs and tehrefore we can name and stdy as any  other organism  giving biorth   to a fielfof ofsyudy alike biology but stdys  organism at  any levekl  of dwvelopemnt, their behavior anbd role in the   evolutionary  mehanism  and continuum. 


## Final Notes
The leap seems to be bigger  than  the papper, but  i'll do my best to suppor my  erasoning and intuiition behiond it. Any  feedback is essention  to the further explorations of the framew