---
title: "staccato/"
format:
  html:
    toc: true
    toc-title: " "
    grid:
      sidebar-width: 300px
      body-width: 400px
      margin-width: 300px
      gutter-width: 1.5rem
author: "Valdetaro, M"
date: "2024-01-23"
categories: [thoughts]
---

### Quick and unsorted daily notes. 
  First transcribed from my physical notebooks. I may not fully transition to a digital-only format so the process analog  --> digital may still apply in the future.

#### On collaboration and defection
Any viable strategy for group collaboration requires a third option,
the freedom to opt out temporarily from the collaboration game. Not deserting
, but an exercise of freedom.

#### Poetry
Poetry is freedom from the scaffolding of Human language.

#### At the Funambule
The impossibility of otherwise obtaining X,
seems to be the main driver of the current economy.
(Bottom up point of view) In a sense, the commodification of possibilities puts a price on freedom. 230324

#### Yesterday night I couldn’t fall asleep
Rapid threads of thoughts traveled through my foreground.  
* How to avoid taxes and end capitalism: a tutorial.   
* Ask your boss to fire you, truth and office politics: a note.   
* Artificial Intelligence and New Citizens Rights: Animal Rights, a note. 10424  

#### date unknown
Adjusting the power distribution in democratic exercise and functions through a revisited direct governance-by-peers framework?

#### date unknown
Not suitable for becomes free of.

#### date unknown

| All my notes from 2022 disappeared and vanished. The notebook got wet, and ink spread.
| PS: investigate how to retrieve memories:
| How are memories encoded?

#### 040423

An inventory for continuous self-discovery

####  031222

Perhaps balance finds us while we’re looking for a purely semantic and abstract concept that does not exist at all.

#### 151122

What would change if an advanced technological civilization existed before 7000 bc? What would that make of us?

#### 151122

Many years ago I started questioning the absurdity of human-generated fiction Now it’s more evident than ever How can one escape the illusion and simply enjoy existence without words with no threads being without being seen?

#### To Youth I

| So be vast, and grow. Fill the emptiness and the hollows with curiosity. 
| Doubt the preceding generation, 
| But not the origin, and the continuum. 
| Go.

#### 210922 -  On Social Systems 

Is the absence of secondary goals a natural state or a capitalist inconvenient? Are inconveniences un-exploitable?

####  .

It's not possible to decapitate an infrastructure.

It daunts me.

####  date unknown

Any kind of self-inflicted suffering is a waste of time.

####  100123                                                     

Self-destruction, unintentional Stars fusing iron the course of availability birds?

Agency → Consciousness → Primal

My existence is nothing Intriguing nonetheless Why are we conscious? Cells aware of their surroundings == local consciousness?

#### date unknown

| All (none) that is permanent and cannot be changed? 
| Even stone is a metamorphic creation and messages carved will (must) erode. 
| Exposing dogmatic beliefs that rotten Human Societies as a weakened act of (r)Evolution. 
| Vēritās līberābit vōs
