---
title: "Education"
author: "Valdetaro, M"
date: "2024-01-20"
categories: [education]
---

We experience education in sequential steps, closed and determined, and are given information and instructions within a perspective of the immutability of reality. "Always was, always will be", sets a stage from where social order re-establishes itself for yet another generation.

Currently education is given a high degree of importance, addressing three major domains:

1.  paralleled with some **future** economic value

2.  paramount for better **future** societies

3.  for an x% increase amount of life-**expectancy**

Amongst the immutability illusion, the doctrine of stability hinders, dangerously close to actual permanent eliminating the core evolutionary device Humans have called learning ability.

Of course, modernity and the Industrial Revolution required literate workers to read the manuals operate machines and assemble products ensuring the life expectancy of the growing assembly line.\
But before that, old clerics required new ones, literate minds to perpetuate the dogmatic pillars of societies.

These devices worked irrefutably for a pair of decades, and after two generations into the Industrial era, two wars eradicated the contextual roots to fundament the newfound modernity within the space-time continuum of existence.

So what we have is the life or death decision to no matter at what cost, participate in the system of preparation of static socio-economic devices.

Given that formal education eradicates the why questions from the equations, and there is a hungry mob of militants enforcing procedures and methods as doctrines, and there is a life or death term in that equation, which legally would constitute an almost certain absolution for any crime, education institutions are the most effective weapons playing a crucial role leading to world destruction.

It's understandable if you disagree, but entertain the thought for a moment, what supports the argument won't take long to pass across, and does the reader have anything to lose:

We are information processing systems, not machines, but systems, of systems of several degrees of agency. There are fantastical and mesmerizing processes of intra-systemic communication, and collaboration that address all scales and allow us to breathe out of our conscious decision.

"Ah, that is just physics", say all the institutions. But you probably don't know that the origin of life is still a mystery, closer and closer to being grasped, but that is another essay.

So far, the argument is made up of:

Education is essential for

1.  some **future** economic value

2.  better **future** societies

3.   x% increase amount of life-**expectancy**

By:

1\. Removing doubt, the why, from a very young age, ensuring social order and forging tacit agreements of fundamental truths

2. Teaching complex systems to repeat the same methods and processes on the dynamic and ever-changing nature of the universe

3\. Promissing those who adhere with dedication and precision and hypothetical better future, based on static doctrines and inductive biases.

Of course, the argument is not fully complete, but is important to juxtapose the information and the principles laid out to re-check if it makes sense. It is important to say at this point that I do not argue that education is bad, nor am I defending illiteracy, child mortality and poverty. The argument is made upon the premise of which education was constituted in the first place., and of course the perversion of incentives pushing the institutionalization of that duty, turning it into a privilege.

But how was the incentive prevented in the first place?

Passing the information down to new generations, to optimize the learning process across long periods, inter-generational learning one may call it, is a evolutionary mechanism developed to prevent extinction, as most life forms on our planet contain. Most species do it in ways we haven't been able to decode, as each system is limited by its perceptual range.

Recapping, our education system:

Education is essential for:

1.  some **future** economic value

2.  better **future** societies

3.  x% increase amount of life-**expectancy**

By:

1.  Removing doubt, the why, from a very young age, ensuring social order and forging tacit agreements of fundamental truths

2.  Teaching complex systems to repeat the same methods and processes on the dynamic and ever-changing nature of the universe

3.  Promissing those who adhere with dedication and precision and hypothetical better future, based on static doctrines and inductive biases.

4.  Being accessible exclusively for a discriminatory and deficient assessment of human potential

5.  Used as an ordering power weapon

6.  Obscuring and obstructing knowledge

7.  Proprietary

Evolution has its selection method, beyond Darwin's linearity. Humans decided to implement Educational systems in place that select who are the fittest by the wrong criteria, hindering the evolutionary process at its core, reducing its agency to -1 device, which took millions of years to evolve.

Humans did it in 100 years.

It's unfathomable that we didn't conceive seriously, at any period, that we know of, to question the nature of learning, why do we learn?

I'm not an expert (break, to be continued )