# Resume

[mvtta.github.io](https://www.mvtta.github.io)

### Summary
```
Name: Valdetaro, Mariana
Current role: Embedded Software Engineer in R&D | 
		      5G Physical Layer at Nokia 
Previous role: Software Engineer Trainee in Applied R&D |
			   Cloud and Networks at Nokia
Looking for: A Software Engineer role in STEM R&D
Why: looking for a new opportunity  to work:
			🔸with impressive humans,
	 		🔸on hard problems,
	 		🔸towards innovation and research.
Mobile: +351967409418 | E-mail: mvaldeta42@gmail.com | Location: Portugal, Europe
```
## Technical Skills
| Languages                               | Tools               | Standards                                                                                 |
| --------------------------------------- | ----------------------------------------------- | ----------------------------------------------------------------------------------------- |
|•C <br> •C++ <br> •bash <br> •learning rust |•git <br> •jira <br> •docker <br> •unix/linux <br> •term <br> •vim |•best practices oriented <br> •documentation <br> •clean atomic code <br> •sw life-cycle |

## Experience <br>
Ten + years of working experience in different fields grant me: <br>
🔸rapid adaptability to new methodologies, <br>
🔸responsability and autonony <br>
🔸intrinsic awareness of time management : delivery, team dynamics and workflow.

| Date            | Job                                                         | Description            |
| --------------- | ----------------------------------------------------------- | ---------------------- |
| April 2023      | Software Engineer in R&D 5G Physical Layer Embedded Systems | Without term           |
| May 1 2022/2023 | Software Engineer Trainee in R&D Cloud and Networks         | Fixed term             |
| 2018/2022       | Founder, manager and operator of R&D studio                 | Without term           |
| 2008/2018       | Sound Engineer & Music Producer                             | Freelance & short term |

## Education
*Self-taught independent degree*, from books and free online resources to payed MOOCs from respected Universities. Some *highlights* bellow:

| Institution                                                              | Course                                                                                                    | Syllabus                                                                                                                                                   | Status                                                                                                                                                                          |
| ------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 42Lisboa                                                                 | Computer Science                                                                                          | C, Algorithms, Memory Management & Graphics                                                                                                                | [Projects](https://github.com/mvtta/42Cursus/tree/main)                                                                                                                            |
| Johns Hopkins University                                          | Neuroscience and Neuroimaging Specialization                                                      | Neuroanatomy & Neuroimaging • Experimental design  • Imaging techniques                                                                  | 2/4 Completed [Certificate 1](https://coursera.org/share/6bd2b93e78b77ce07101d9de16de85fe)  [Certificate 2](https://coursera.org/share/70e18a2cafdca8b3a381d59d346ea25c) |
| Johns Hopkins University                                                 | Precalculus through Data and Modelling Mathematics Specialization                                 | • Function analysis • Vectors, Vector Spaces and Operations  • Regression & Data Analysis                                      | [Certificate 1](https://coursera.org/share/d0971110f05e87781130c6342fd62b75)                                                                                                       |
| Korea Advanced  Institute of Science  and Technology(KAIST) | [Introduction to Quantum Information](https://www.coursera.org/learn/introduction-to-quantum-information)    | • Axioms of Quantum Theory • Qubit Experiment  State Transformation VS. Probabilities  Quantum Computing & Quantum Communication | In progress⚙️                                                                                                                                                                 |
| Icahn School of Medicine at Mount Sinai                           | [Systems Biology and Biotechnology Specialization](https://www.coursera.org/specializations/systems-biology) |                                                                                                                                                            |   In queue                                                                                                                                                                              |

Thank you for your time, 
``Sincerely Mariana ``.