# Resume

[mvtta.github.io](https://www.mvtta.github.io)

### Summary

```         
Name: Valdetaro, Mariana
Current role: R&D L1Phy Software Engineer @ Nokia 
(Telecom, Networks, Embedded Systems, \
Radio Technology, Information Theory)

Looking for a cross-field opportunity in Research and Development to
            • Learn with, and meet inspiring humans,
            • On the interconnectedness of all problems,
            • Towards a Planetary Future.

Mobile: +351967409418 | E-mail: mvaldeta42@gmail.com | Location: Portugal, Europe
```

## Experience <br>

(Still editing, just rambling for now)

(Still editing, just rambling for now)

I have a rich, diverse, and broad spectrum of occupational experiences.

Working in a restaurant frequented by audiophiles was where I got my start. Different groups of customers would extend me invitations to attend musical events, which sparked my interest in the physical aspects of sound, both in the engineering and anthropological senses.

I listened to them talk for hours and eventually learned their dialect.

After six months I changed to a bar, at night, while seizing an opportunity during the day as a hairdresser's assistant.

Her customers were artists, writers, fashion designers, musicians, and lots of foreigners, I would silently and swiftly attend to her needs, personal and technical, run errands, contact suppliers, wash customers' hair, and clean. She was demanding, but brilliant.

I observed people would come and go, and so did their universes. All different and complex.

Apart from events, film, and photo-shoot days, my routine was ritualistic, like a synchronized dance of being present and anticipating, my English skills matured, my visual culture grew, and I was within reach of beautiful books and art magazines.

After four years, I decided to dedicate myself more to music and did my first tour through Portugal as a disk-jockey duo. We were on a lot of buses, I could read many hours in a row. The customers were large groups or crowds, and the interactions changed. My colleagues were sound technicians, bartenders, and dancers. I didn't like performing in general, although I felt like an honor to share that unique moment with strangers.

Opaque mediums of exchange, loneliness, suffering, and superficial hope. I found that performing in clubs was extremely sad, but it was a small part compared to commuting, reading, and thinking, I enjoyed that part.

Since that time, plus six years, founded a company that mirrored my interests, from material science, visual culture, and semiotics, and consulted for mineral extraction and production industries in Portugal. I lived in Japan for 2 years and collaborated at the initial stage of a new business development platform in the start-up city of Japan, Fukuoka. It was an important moment, as the depth of the connections between ideas, problems, and outcomes emerged vividly in my perceptual model.

Optimistic and humbled by this phase of my life, it culminated in the materialization of immaterial product development for the quarry industry of Portugal, an homage to the metamorphic device of space and time, life-giving life different form, marble stone as the agents of time, like gods, watching Humans.

As a commissioned thought process, the message was conveyed through a movie, our crew was small, and the sacrifices were proportional to the cause. To humanize the objective, a garment collection with biodegradable materials, and hand made was shown at a fashion event and then converted from analog to digital where anyone could interact with it, transform it through gestures if holding a marble device, shaped like a mobile phone, without a screen, that had no instructions, the discovery and interaction where experimental.

I learned that most didn't understand, and some were even embarrassed - discomfort, over the experimental nature of the project, but I did change something, the government agency representing mineral resources then appropriated them elves with a language created, and although distorted by greed and vanity, the seed of the message became the new norm to speak, price and sell Portuguese marble stone.

All I'd read about economics, supply, and demand, marketing, and Human behavior did not match the entrepreneurial expression around me, I was no longer optimistic. No value was being created, value was being destroyed and applauded. If the government had no check on their decisions, and neglected the citizens, private initiative had a huge responsibility in the social domain, as I previously thought.

For that reason, I had read more about governance, decentralization, re-distribution, biology, and geometry, and slightly before the pandemic, I realized that different nodes were infecting social bodies with infinite loops of redundancy. I created Reboot, a platform for makers around the world to connect directly with potential end customers, to produce in a made-to-order fashion, cutting transactional costs both in proceeds and logistics, hoping to preserve what was left of cultural heritage in developing economies, freeing fragile communities from exploitation, and by strategic pricing according to local economy, a yearly re-distribution of the companies profit would act as an insurance for the Humans relying on the platform, to make their means be met.

It felt like a great idea, investors all around the world said it was a great idea. They would connect me to a friend, and then another board director, amounting to nothing. The bootstrapping myth led reboot to the end of our runway, and I was compelled to learn Computer Science from a practical approach. I was accepted into a school, sponsored by patrons, that offered a free course called 42 School.

This was 2020, and I have been devoting ~80% of my energy to learning and improving to help me think with tools I now understand how to use and incorporate with the previous ones.

For the first time, I have a corporate job, where hyper-specialization is the trait of the enlightened. My performance is slightly above average, considering my non-seniority status, but to attain it, I internalize a great cost, and the output is nothing. It doesn't make sense. I'm not directly developing any product, but I don't have a narrow vision of problems, and to reduce the scope is forging the problems of tomorrow.

My current occupation is entertaining and distracting, nonetheless, but is not meaningful, and it hinders all the differences I was born with, and what I can contribute to the planet and society.

## Technical Skills

| Languages                                   | Tools                                                                | Standards                                                                                |
|------------------|-------------------|-----------------------------------|
| •C <br> •C++ <br> •bash <br> •learning rust | •git <br> •jira <br> •docker <br> •unix - linux <br> •term <br> •vim | •best practices oriented <br> •documentation <br> •clean atomic code <br> •sw life-cycle |

## Experience <br>

I have a rich, diverse and broad spectrum of occupational experiences.

| Date            | Job                                                         | Description            |
|----------------|-----------------------------------------|----------------|
| April 2023      | Software Engineer in R&D 5G Physical Layer Embedded Systems | Without term           |
| May 1 2022/2023 | Software Engineer Trainee in R&D Cloud and Networks         | Fixed term             |
| 2018/2022       | Founder, manager and operator of R&D studio                 | Without term           |
| 2008/2018       | Sound Engineer & Music Producer                             | Freelance & short term |

## Education

*Self-taught independent degree*.
Some *highlights* bellow:

| Institution                                               | Course                                                                                                       | Syllabus                                                                                                                       | Status                                                                                                                                                                  |
|----------------|----------------|-------------------|----------------------|
| 42Lisboa                                                  | Computer Science                                                                                             | C, Algorithms, Memory Management & Graphics                                                                                    | [Projects](https://github.com/mvtta/42Cursus/tree/main)                                                                                                                 |
| Johns Hopkins University                                  | Neuroscience and Neuroimaging Specialization                                                                 | Neuroanatomy & Neuroimaging • Experimental design • Imaging techniques                                                         | 2/4 Completed [Certificate 1](https://coursera.org/share/6bd2b93e78b77ce07101d9de16de85fe) [Certificate 2](https://coursera.org/share/70e18a2cafdca8b3a381d59d346ea25c) |
| Johns Hopkins University                                  | Precalculus through Data and Modelling Mathematics Specialization                                            | • Function analysis • Vectors, Vector Spaces and Operations • Regression & Data Analysis                                       | [Certificate 1](https://coursera.org/share/d0971110f05e87781130c6342fd62b75)                                                                                            |
| Korea Advanced Institute of Science and Technology(KAIST) | [Introduction to Quantum Information](https://www.coursera.org/learn/introduction-to-quantum-information)    | • Axioms of Quantum Theory • Qubit Experiment State Transformation VS. Probabilities Quantum Computing & Quantum Communication | In progress⚙️                                                                                                                                                           |
| Icahn School of Medicine at Mount Sinai                   | [Systems Biology and Biotechnology Specialization](https://www.coursera.org/specializations/systems-biology) |                                                                                                                                | In queue                                                                                                                                                                |

Thank you for your appreciation, `Sincerely Mariana`.